# TCL File Generated by Component Editor 13.1
# Mon Jun 20 13:18:19 EDT 2016
# DO NOT MODIFY


# 
# sampler "sampler" v1.0
# Aaron Griffith 2016.06.20.13:18:19
# Memory-mapped sampler that records its inputs for a short burst of time.
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sampler
# 
set_module_property DESCRIPTION "Memory-mapped sampler that records its inputs for a short burst of time."
set_module_property NAME sampler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Aaron Griffith"
set_module_property DISPLAY_NAME sampler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property ELABORATION_CALLBACK elaborate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qsys_sampler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sampler.v VERILOG PATH sampler.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL qsys_sampler
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sampler.v VERILOG PATH sampler.v


# 
# parameters
#
add_parameter inputBits POSITIVE 1 "number of bits of data to record at each step"
set_parameter_property inputBits DEFAULT_VALUE 32
set_parameter_property inputBits DISPLAY_NAME "Input Width"
set_parameter_property inputBits WIDTH ""
set_parameter_property inputBits TYPE POSITIVE
set_parameter_property inputBits UNITS bits
set_parameter_property inputBits ALLOWED_RANGES 1:32768
set_parameter_property inputBits DESCRIPTION ""
set_parameter_property inputBits HDL_PARAMETER false
set_parameter_property inputBits DESCRIPTION "number of bits of data to record at each step"
add_parameter words POSITIVE 1 "number of 32 bit words of data to record at each step"
set_parameter_property words DERIVED true
set_parameter_property words DEFAULT_VALUE 1
set_parameter_property words DISPLAY_NAME "Input Width (in 32-bit Words)"
set_parameter_property words WIDTH ""
set_parameter_property words TYPE POSITIVE
set_parameter_property words UNITS None
set_parameter_property words ALLOWED_RANGES 1:1024
set_parameter_property words DESCRIPTION ""
set_parameter_property words HDL_PARAMETER true
set_parameter_property words DESCRIPTION "number of 32 bit words of data to record at each step"
add_parameter words_log_2 NATURAL 0 "number of 32 bit words of data to record at each step (log-2'd)"
set_parameter_property words_log_2 DERIVED true
set_parameter_property words_log_2 DEFAULT_VALUE 0
set_parameter_property words_log_2 DISPLAY_NAME "Input Width (log2)"
set_parameter_property words_log_2 WIDTH ""
set_parameter_property words_log_2 TYPE NATURAL
set_parameter_property words_log_2 UNITS None
set_parameter_property words_log_2 ALLOWED_RANGES 0:10
set_parameter_property words_log_2 DESCRIPTION "number of 32 bit words of data to record at each step (log-2'd)"
set_parameter_property words_log_2 HDL_PARAMETER true
add_parameter timeBits NATURAL 10 "number of bits of time data to keep"
set_parameter_property timeBits DEFAULT_VALUE 10
set_parameter_property timeBits DISPLAY_NAME "Time Width"
set_parameter_property timeBits WIDTH ""
set_parameter_property timeBits TYPE POSITIVE
set_parameter_property timeBits UNITS bits
set_parameter_property timeBits ALLOWED_RANGES 1:32
set_parameter_property timeBits DESCRIPTION "number of bits of time data to keep"
set_parameter_property timeBits HDL_PARAMETER true
add_parameter addrBits POSITIVE 1 "total bits of address space occupied"
set_parameter_property addrBits DERIVED true
set_parameter_property addrBits DEFAULT_VALUE 12
set_parameter_property addrBits DISPLAY_NAME "Address Size"
set_parameter_property addrBits WIDTH ""
set_parameter_property addrBits TYPE POSITIVE
set_parameter_property addrBits UNITS bits
set_parameter_property addrBits ALLOWED_RANGES 1:32
set_parameter_property addrBits DESCRIPTION ""
set_parameter_property addrBits HDL_PARAMETER false
set_parameter_property addrBits DESCRIPTION "total bits of address space occupied"

#
# elaboration
#
proc elaborate {} {
    set our_bits [get_parameter_value inputBits]
    set our_words [expr {ceil($our_bits / 32.0)}]
    set our_words_log_2 [expr {ceil(log($our_words)/log(2))}]
    set our_time_bits [get_parameter_value timeBits]
    set our_addr_bits [expr {$our_words_log_2 + 2 + $our_time_bits}]
    set_parameter_value words $our_words
    set_parameter_value words_log_2 $our_words_log_2
    set_parameter_value addrBits $our_addr_bits
}


# 
# display items
# 


# 
# connection point read_clk
# 
add_interface read_clk clock end
set_interface_property read_clk clockRate 0
set_interface_property read_clk ENABLED true
set_interface_property read_clk EXPORT_OF ""
set_interface_property read_clk PORT_NAME_MAP ""
set_interface_property read_clk CMSIS_SVD_VARIABLES ""
set_interface_property read_clk SVD_ADDRESS_GROUP ""

add_interface_port read_clk clk clk Input 1


# 
# connection point read_reset
# 
add_interface read_reset reset end
set_interface_property read_reset associatedClock read_clk
set_interface_property read_reset synchronousEdges DEASSERT
set_interface_property read_reset ENABLED true
set_interface_property read_reset EXPORT_OF ""
set_interface_property read_reset PORT_NAME_MAP ""
set_interface_property read_reset CMSIS_SVD_VARIABLES ""
set_interface_property read_reset SVD_ADDRESS_GROUP ""

add_interface_port read_reset reset_n reset_n Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock read_clk
set_interface_property csr associatedReset read_reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input 8
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 8
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point read
# 
add_interface read avalon end
set_interface_property read addressUnits WORDS
set_interface_property read associatedClock read_clk
set_interface_property read associatedReset read_reset
set_interface_property read bitsPerSymbol 8
set_interface_property read burstOnBurstBoundariesOnly false
set_interface_property read burstcountUnits WORDS
set_interface_property read explicitAddressSpan 0
set_interface_property read holdTime 0
set_interface_property read linewrapBursts false
set_interface_property read maximumPendingReadTransactions 0
set_interface_property read readLatency 0
set_interface_property read readWaitTime 1
set_interface_property read setupTime 0
set_interface_property read timingUnits Cycles
set_interface_property read writeWaitTime 0
set_interface_property read ENABLED true
set_interface_property read EXPORT_OF ""
set_interface_property read PORT_NAME_MAP ""
set_interface_property read CMSIS_SVD_VARIABLES ""
set_interface_property read SVD_ADDRESS_GROUP ""

add_interface_port read buffer_read read Input 1
add_interface_port read buffer_address address Input timeBits+words_log_2
add_interface_port read buffer_readdata readdata Output 32
set_interface_assignment read embeddedsw.configuration.isFlash 0
set_interface_assignment read embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment read embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment read embeddedsw.configuration.isPrintableDevice 0


# 
# connection point done
# 
add_interface done interrupt end
set_interface_property done associatedAddressablePoint csr
set_interface_property done associatedClock read_clk
set_interface_property done associatedReset read_reset
set_interface_property done ENABLED true
set_interface_property done EXPORT_OF ""
set_interface_property done PORT_NAME_MAP ""
set_interface_property done CMSIS_SVD_VARIABLES ""
set_interface_property done SVD_ADDRESS_GROUP ""

add_interface_port done irq irq Output 1


# 
# connection point sample_clk
# 
add_interface sample_clk clock end
set_interface_property sample_clk clockRate 0
set_interface_property sample_clk ENABLED true
set_interface_property sample_clk EXPORT_OF ""
set_interface_property sample_clk PORT_NAME_MAP ""
set_interface_property sample_clk CMSIS_SVD_VARIABLES ""
set_interface_property sample_clk SVD_ADDRESS_GROUP ""

add_interface_port sample_clk w_clk clk Input 1


# 
# connection point sample_reset
# 
add_interface sample_reset reset start
set_interface_property sample_reset associatedClock read_clk
set_interface_property sample_reset associatedDirectReset ""
set_interface_property sample_reset associatedResetSinks read_reset
set_interface_property sample_reset synchronousEdges DEASSERT
set_interface_property sample_reset ENABLED true
set_interface_property sample_reset EXPORT_OF ""
set_interface_property sample_reset PORT_NAME_MAP ""
set_interface_property sample_reset CMSIS_SVD_VARIABLES ""
set_interface_property sample_reset SVD_ADDRESS_GROUP ""

add_interface_port sample_reset w_reset_n reset_n Output 1


# 
# connection point sample
# 
add_interface sample conduit end
set_interface_property sample associatedClock sample_clk
set_interface_property sample associatedReset ""
set_interface_property sample ENABLED true
set_interface_property sample EXPORT_OF ""
set_interface_property sample PORT_NAME_MAP ""
set_interface_property sample CMSIS_SVD_VARIABLES ""
set_interface_property sample SVD_ADDRESS_GROUP ""

add_interface_port sample w_in export Input 32*words
