# TCL File Generated by Component Editor 13.1
# Thu Jun 16 15:42:11 EDT 2016
# DO NOT MODIFY


# 
# sampler "sampler" v1.0
#  2016.06.16.15:42:11
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sampler
# 
set_module_property DESCRIPTION ""
set_module_property NAME sampler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sampler
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qsys_sampler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sampler.v VERILOG PATH sampler.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL qsys_sampler
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sampler.v VERILOG PATH sampler.v


# 
# parameters
# 
add_parameter words_log_2 NATURAL 0 ""
set_parameter_property words_log_2 DEFAULT_VALUE 0
set_parameter_property words_log_2 DISPLAY_NAME words_log_2
set_parameter_property words_log_2 WIDTH ""
set_parameter_property words_log_2 TYPE NATURAL
set_parameter_property words_log_2 UNITS None
set_parameter_property words_log_2 ALLOWED_RANGES 0:2147483647
set_parameter_property words_log_2 DESCRIPTION ""
set_parameter_property words_log_2 HDL_PARAMETER true
add_parameter words POSITIVE 1 "must be 2**words_log_2"
set_parameter_property words DEFAULT_VALUE 1
set_parameter_property words DISPLAY_NAME words
set_parameter_property words WIDTH ""
set_parameter_property words TYPE POSITIVE
set_parameter_property words UNITS None
set_parameter_property words ALLOWED_RANGES 1:2147483647
set_parameter_property words DESCRIPTION "must be 2**words_log_2"
set_parameter_property words HDL_PARAMETER true
add_parameter timeBits NATURAL 10 ""
set_parameter_property timeBits DEFAULT_VALUE 10
set_parameter_property timeBits DISPLAY_NAME timeBits
set_parameter_property timeBits WIDTH ""
set_parameter_property timeBits TYPE NATURAL
set_parameter_property timeBits UNITS None
set_parameter_property timeBits ALLOWED_RANGES 0:2147483647
set_parameter_property timeBits DESCRIPTION ""
set_parameter_property timeBits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock read_clk
set_interface_property csr associatedReset read_reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input 8
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 8
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point read_clk
# 
add_interface read_clk clock end
set_interface_property read_clk clockRate 0
set_interface_property read_clk ENABLED true
set_interface_property read_clk EXPORT_OF ""
set_interface_property read_clk PORT_NAME_MAP ""
set_interface_property read_clk CMSIS_SVD_VARIABLES ""
set_interface_property read_clk SVD_ADDRESS_GROUP ""

add_interface_port read_clk clk clk Input 1


# 
# connection point read_buffer
# 
add_interface read_buffer avalon end
set_interface_property read_buffer addressUnits WORDS
set_interface_property read_buffer associatedClock read_clk
set_interface_property read_buffer associatedReset read_reset
set_interface_property read_buffer bitsPerSymbol 8
set_interface_property read_buffer burstOnBurstBoundariesOnly false
set_interface_property read_buffer burstcountUnits WORDS
set_interface_property read_buffer explicitAddressSpan 0
set_interface_property read_buffer holdTime 0
set_interface_property read_buffer linewrapBursts false
set_interface_property read_buffer maximumPendingReadTransactions 0
set_interface_property read_buffer readLatency 0
set_interface_property read_buffer readWaitTime 1
set_interface_property read_buffer setupTime 0
set_interface_property read_buffer timingUnits Cycles
set_interface_property read_buffer writeWaitTime 0
set_interface_property read_buffer ENABLED true
set_interface_property read_buffer EXPORT_OF ""
set_interface_property read_buffer PORT_NAME_MAP ""
set_interface_property read_buffer CMSIS_SVD_VARIABLES ""
set_interface_property read_buffer SVD_ADDRESS_GROUP ""

add_interface_port read_buffer buffer_read read Input 1
add_interface_port read_buffer buffer_address address Input timeBits+words_log_2
add_interface_port read_buffer buffer_readdata readdata Output 32
set_interface_assignment read_buffer embeddedsw.configuration.isFlash 0
set_interface_assignment read_buffer embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment read_buffer embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment read_buffer embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sample
# 
add_interface sample conduit end
set_interface_property sample associatedClock sample_clk
set_interface_property sample associatedReset ""
set_interface_property sample ENABLED true
set_interface_property sample EXPORT_OF ""
set_interface_property sample PORT_NAME_MAP ""
set_interface_property sample CMSIS_SVD_VARIABLES ""
set_interface_property sample SVD_ADDRESS_GROUP ""

add_interface_port sample w_in export Input 32*words


# 
# connection point sample_clk
# 
add_interface sample_clk clock end
set_interface_property sample_clk clockRate 0
set_interface_property sample_clk ENABLED true
set_interface_property sample_clk EXPORT_OF ""
set_interface_property sample_clk PORT_NAME_MAP ""
set_interface_property sample_clk CMSIS_SVD_VARIABLES ""
set_interface_property sample_clk SVD_ADDRESS_GROUP ""

add_interface_port sample_clk w_clk clk Input 1


# 
# connection point read_reset
# 
add_interface read_reset reset end
set_interface_property read_reset associatedClock read_clk
set_interface_property read_reset synchronousEdges DEASSERT
set_interface_property read_reset ENABLED true
set_interface_property read_reset EXPORT_OF ""
set_interface_property read_reset PORT_NAME_MAP ""
set_interface_property read_reset CMSIS_SVD_VARIABLES ""
set_interface_property read_reset SVD_ADDRESS_GROUP ""

add_interface_port read_reset reset_n reset_n Input 1


# 
# connection point done
# 
add_interface done interrupt end
set_interface_property done associatedAddressablePoint ""
set_interface_property done associatedClock read_clk
set_interface_property done associatedReset read_reset
set_interface_property done ENABLED true
set_interface_property done EXPORT_OF ""
set_interface_property done PORT_NAME_MAP ""
set_interface_property done CMSIS_SVD_VARIABLES ""
set_interface_property done SVD_ADDRESS_GROUP ""

add_interface_port done irq irq Output 1

